name: "Generate"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  generate:
    name: "Generate"
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Login account"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Delete defaults"
        run: |
          rm -rf ./src/defaults.json

      - name: "Generate defaults"
        run: |
          az account list-locations -o json \
            | jq '{"regions": [.[] | {"name": .name, "displayName": .displayName, "country": .metadata.geography, "city": .metadata.physicalLocation, "availabilityZones": (.availabilityZoneMappings | length > 0)}] | sort_by(.name)}' \
            | > ./src/defaults.json

      - name: "Show defaults"
        run: |
          cat ./src/defaults.json

      - name: "Configure git"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: "Merge defaults"
        run: |
          if [ -n "$(git status gen/ --porcelain)" ]; then
            git checkout -b gen/defaults
            git add src/defaults.json
            git commit -m 'gen: update defaults'
            git push origin gen/defaults
            gh pr create --title "gen: update defaults" --body ""
            gh pr merge gen/defaults --auto --squash
          fi

      - name: "Delete runs"
        run: |
          month=$(date -d "$(date +%Y-%m)-15 last month" '+%Y-%m')
          gh run list --created $month --json databaseId --jq '.[].databaseId' --limit 50 | xargs -I{} gh run delete {}
